Atualização: libdvdread, k9copy, kqemu. Adicionado: digikam, libkexif, imlib2, exiv2, libkipi
git-svn-id: svn+slack://slack.fluxo.info/var/svn/slackbuilds@608 370017ae-e619-0410-ac65-c121f96126d4

diff --git a/exiv2/exiv2.SlackBuild b/exiv2/exiv2.SlackBuild
--- a/exiv2/exiv2.SlackBuild
+++ b/exiv2/exiv2.SlackBuild
@@ -1,11 +1,12 @@
 #!/bin/bash
 #
-# slackbuild for Qemu, by Rudson R. Alves
-# requires: qemu
-# tested: kqemu-1.3.0pre9
+# slackbuild for exiv2, by Rudson R. Alves
+# requires: none
+# tested: exiv2-0.11
 
 CWD=`pwd`
 
+# ----  Inicializa variáveis com o slackbuild  ------------
 if [ -e "/root/.slackbuildrc" ]; then
   source /root/.slackbuildrc
 elif [ -e "/etc/slackbuildrc" ]; then
@@ -15,9 +16,10 @@ fi
 # --------  Variáveis de controle de versão  --------------
 # Nome da fonte para a qual o slackbuild foi construído e
 # o seu md5sum
-SRC_ORIG="kqemu-1.3.0pre9.tar.gz"
-MD5_ORIG="27888c3220844ad360a6a23345fa1bcb"
-VERSION_ORIG="1.3.0" #`echo $SRC_ORIG | sed 's/\(.*\)-\(.*\)\.\(.*\..*\)$/\2/'`
+SRC_ORIG="exiv2-0.11.tar.gz"
+MD5_ORIG="269ce822946c56549d086f0c08dffc79"
+PACKAGE_ORIG=`echo $SRC_ORIG | sed 's/\(.*\)-\(.*\)\.\(.*\..*\)$/\1/'`
+VERSION_ORIG=`echo $SRC_ORIG | sed 's/\(.*\)-\(.*\)\.\(.*\..*\)$/\2/'`
 EXTENSION=`echo $SRC_ORIG | sed 's/\(.*\)-\(.*\)\.\(.*\..*\)$/\3/'`
 
 # -------  Códigos de erro para o createpkg  --------------
@@ -27,25 +29,18 @@ ERROR_TAR=37;       ERROR_MKPKG=38;     ERROR_GPG=39
 ERROR_PATCH=40;     ERROR_VCS=41
 
 # ---------  Inicializa variáveis de entrada  -------------
-PACKAGE=`echo $SRC_ORIG | sed 's/\(.*\)-\(.*\)\.\(.*\..*\)$/\1/'`
+PACKAGE=$PACKAGE_ORIG
 ARCH=${ARCH:=i468}
 SRC_DIR=${SRC:=$CWD}
-if [ "$VERSION" != "" ]; then
-    # Constroi nome do pacote
-    SRC=$PACKAGE-$VERSION.$EXTENSION
-else
-    # Remove nome e versão do pacote
-    SRC=$SRC_ORIG
-    VERSION=$VERSION_ORIG
-fi
+VERSION=${VERSION:=$VERSION_ORIG}
+SRC=$PACKAGE-$VERSION.$EXTENSION
 BUILD=${BUILD:=1rud}
 TMP=${TMP:=/tmp}
 REPOS=${REPOS:=$TMP}
 PREFIX=${PREFIX:=/usr}
 OPTCONF=${OPTCONF:=""}
 MD5=${MD5:=$MD5_ORIG}
-URL=${URL:="http://fabrice.bellard.free.fr/qemu/$SRC"}
-KVERSION=`uname -r | tr - _ `
+URL=${URL:="http://www.exiv2.org/$SRC"}
 
 # ----------------  SlackBuild Help  ----------------------
 if [ "$1" = "--help" -o "$1" = "help" ]; then
@@ -70,12 +65,11 @@ fi
 
 # ----------------  Download fontes  ----------------------
 # Fonte a ser compilada, com o path
-SOURCE=$SRC_DIR/qemu/$SRC
-mkdir -p $SRC_DIR/qemu 2>/dev/null
+SOURCE=$SRC_DIR/$PACKAGE/$SRC
 # Verifica existência do pacote em $SRC em $SRC_DIR
 if [ ! -e $SOURCE ]; then
     echo -e "\n\n\033[01;32m Download $PACKAGE \n\033[m"
-    wget "$URL" -P "$SRC_DIR/qemu/"
+    wget "$URL" -P "$SRC_DIR/$PACKAGE"
     # Verifica se o
     if [ $? -ne 0 ]; then
         echo -e "\n\n\033[01;31m No such source file in $URL\n\033[m"
@@ -89,7 +83,7 @@ if [ "$SRC_ORIG" = "$SRC" -o "$MD5" != "$MD5_ORIG" -a "$MD5" != "no" ]; then
     if [ "$SUM" != "$MD5" ]; then
         echo -e "\n\n\033[01;31m MD5SUM error: run Slackbuild again \n\033[m"
         echo -e "\033[01;31m Remove $PACKAGE from $SRC_DIR and start Slackbuild again or use MD5=\"no\" \n\033[m"
-        exit $ERROR_MD5
+        exit 0
     fi
     echo -e "\n\n\033[01;32m Md5sum Ok \n\033[m"
 fi
@@ -112,12 +106,12 @@ elif [ "$ARCH" = "x86_64" ]; then
 fi
 
 # --------------  Desempacota fontes  ---------------------
-# Desempacota fontes em $TMP/$PACKAGE-source
+# Desempacota fontes em PKG_SRC=$TMP/$PACKAGE-source
 PKG_SRC=$TMP/$PACKAGE-source
 rm -rf $PKG_SRC 2>/dev/null
 mkdir -p $PKG_SRC
 # Desempacota $SOURCE em $TMP/$PACKAGE-source
-tar xvf $SOURCE -C $PKG_SRC 2>/dev/null
+tar xvf $SOURCE -C $PKG_SRC
 if [ $? -ne 0 ]; then
     echo -e "\n\n\033[01;31m $SOURCE file error \n\033[m"
     exit $ERROR_TAR
@@ -141,7 +135,7 @@ echo -e "\n\n\033[01;32m make -j3 \n\033[m"
 make -j3
 if [ $? -ne 0 ]; then
     echo -e "\n\n\033[01;31m Build error \n\033[m"
-    exit 0
+    exit $ERROR_MAKE
 fi
 
 # -------------  Diretório Temporário  --------------------
@@ -151,64 +145,24 @@ rm -rf $PKG
 mkdir -p $PKG
 
 # ---------------  Instala programa  ----------------------
-#           #### Instalação de binários #####
 # Instala programa em diretório temporário
-echo -e "\n\n\033[01;32m Install $PACKAGE in $PKG \n\033[m"
-
-# Find module name
-if [ -f kqemu.ko ] ; then
-   MODULE=kqemu.ko
-else
-   MODULE=kqemu.o
+echo -e "\n\n\033[01;32m make install DESTDIR=$PKG \n\033[m"
+make install DESTDIR=$PKG
+if [ $? -ne 0 ]; then
+    echo -e "\n\n\033[01;31m Install error \n\033[m"
+    exit $ERROR_INSTALL
 fi
-
-# Find kernel install path
-KERNEL_PATH="/lib/modules/`uname -r`"
-
-mkdir -p "$PKG/$KERNEL_PATH/misc"
-cp "$MODULE" "$PKG/$KERNEL_PATH/misc"
-#            #### Fim da instalação #####
+# ---------------  Compacta manuais  ----------------------
+gzip -r $PKG/shared/man/*
 
 # -----------------  Stripa código  -----------------------
 cd $PKG
 find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 
-# ----------------  Cria doinstall  ----------------------
-# Script de instalação
-mkdir $PKG/install
-
-echo -e "\n\n\033[01;32m doinst.sh \n\033[m"
-cat << EOF_DONINST > install/doinst.sh
-#!/bin/sh
-set +e
-MODFILE=/etc/rc.d/rc.local
-
-/sbin/depmod -a
-
-# Create the kqemu device. No special priviledge is needed to use kqemu.
-DEVICE="/dev/kqemu"
-rm -f \$DEVICE
-mknod \$DEVICE c 250 0
-chmod 666 \$DEVICE
-
-MODULE=\$(grep 'kqemu' \$MODFILE)
-if [ "\$MODULE" = "" ]; then
-    echo "# Loading kqemu module" >> \$MODFILE
-    echo "/sbin/modprobe kqemu" >> \$MODFILE
-    echo "echo 1024 > /proc/sys/dev/rtc/max-user-freq" >> \$MODFILE
-else
-    echo -e "\nCheck kqemu mudules install in \$MODFILE\n"
-fi
-echo "Loading kqemu module"
-/sbin/modprobe kqemu
-echo 1024 > /proc/sys/dev/rtc/max-user-freq
-EOF_DONINST
-
 # ----------------  Cria slack-desc  ----------------------
-# Slack-desc
-echo -e "\n\n\033[01;32m slack-desc \n\033[m"
-cat << EOF_SLACK > install/slack-desc
+mkdir $PKG/install
+cat << EOF > install/slack-desc
 # HOW TO EDIT THIS FILE:
 # The "handy ruler" below makes it easier to edit a package description.  Line
 # up the first '|' above the ':' following the base package name, and the '|' on
@@ -216,29 +170,29 @@ cat << EOF_SLACK > install/slack-desc
 # exactly 11 lines for the formatting to be correct.  It's also customary to
 # leave one space after the ':'.
 
-     |--------handy-ruler------------------------------------------------------|
-kqemu: KQEMU package by Rudson R. Alves <rudsonalves[a]yahoo.com.br>
-kqemu:
-kqemu: QEMU Accelerator (KQEMU) is a driver allowing the QEMU PC emulator to
-kqemu: run much faster when emulating a PC on an x86 host.
-kqemu:
-kqemu: KQEMU is supported on x86 or x86_64 Linux 2.4 or 2.6 hosts. Experimental
-kqemu: versions are available for FreeBSD and Windows NT/2000/2003/XP.
-kqemu:
-kqemu:
-kqemu:
-kqemu:
-EOF_SLACK
+      |--------handy-ruler------------------------------------------------------|
+exiv2: libdvdread.SlackBuild by Rudson R. Alves
+exiv2:
+exiv2: Exiv2 is a C++ library and a command line utility to access image
+exiv2: metadata. Exiv2 is available as free software and with a commercial
+exiv2: license, and is used in a growing number of projects.
+exiv2: The Exiv2 library provides:
+exiv2: - full read and write access to the Exif and IPTC metadata of an
+exiv2: image through Exiv2 keys and standard C++ iterators
+exiv2: - a smart IPTC implementation that does not affect data that
+exiv2: programs like Photoshop store in the same image segment, ...
+EOF
 
 # -----------------  Documentações  -----------------------
 # Criar diretório de documentação
 PKG_DOC=$PKG/usr/doc/$PACKAGE-$VERSION
 mkdir -p $PKG_DOC
-cp $PKG_DIR/{Changelog,LICENSE,README} $PKG_DOC
+cp $PKG_DIR/{COPYING,README} $PKG_DOC
+cp -r $PKG_DIR/doc $PKG_DOC
 
 # ---------------  Constroi o pacote  ---------------------
 echo -e "\n\n\033[01;32m makepkg -c y -l y $REPOS/$PACKAGE-$VERSION-$ARCH-$BUILD.tgz \n\033[m"
-makepkg -c y -l y $REPOS/$PACKAGE-$VERSION"_"$KVERSION-$ARCH-$BUILD.tgz
+makepkg -c y -l y $REPOS/$PACKAGE-$VERSION-$ARCH-$BUILD.tgz
 if [ $? -ne 0 ]; then
     exit $ERROR_MKPKG
 fi
