ladspa: small fix
git-svn-id: svn+slack://slack.fluxo.info/var/svn/slackbuilds@386 370017ae-e619-0410-ac65-c121f96126d4

diff --git a/ladspa/ladspa.SlackBuild b/ladspa/ladspa.SlackBuild
--- a/ladspa/ladspa.SlackBuild
+++ b/ladspa/ladspa.SlackBuild
@@ -76,7 +76,7 @@ cd src
 sed -e 's/\/usr\/local\/lib\/ladspa\//\/usr\/lib\/ladspa\//' \
     -e 's/\/usr\/local\/bin\//\/usr\/bin\//' makefile > makefile.tmp || exit $ERROR_CONF
 
-echo 'PREFIX = $TMP/package-$PACKAGE' >> makefile.tmp || exit $ERROR_CONF
+echo "PREFIX = $TMP/package-$PACKAGE" >> makefile.tmp || exit $ERROR_CONF
 
 sed -e 's/$(INSTALL_PLUGINS_DIR)/$(PREFIX)\/$(INSTALL_PLUGINS_DIR)/g' \
     -e 's/$(INSTALL_INCLUDE_DIR)/$(PREFIX)\/$(INSTALL_INCLUDE_DIR)/g' \
