gconf: updating gconf and adding dependencies (thanks x-doctor)
git-svn-id: svn+slack://slack.fluxo.info/var/svn/slackbuilds@2260 370017ae-e619-0410-ac65-c121f96126d4

diff --git a/sys/libs/linux-pam/linux-pam.SlackBuild b/sys/libs/linux-pam/linux-pam.SlackBuild
--- a/sys/libs/linux-pam/linux-pam.SlackBuild
+++ b/sys/libs/linux-pam/linux-pam.SlackBuild
@@ -1,11 +1,11 @@
 #!/bin/bash
 #
-#  GConf.SlackBuild is free software; you can redistribute
+#  linux-pam.SlackBuild is free software; you can redistribute
 #  it and/or modify it under the terms of the GNU General Public License as
 #  published by the Free Software Foundation; either version 2 of the License,
 #  or any later version.
 #
-#  GConf.SlackBuild is distributed in the hope that it will
+#  linux-pam.SlackBuild is distributed in the hope that it will
 #  be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
 #  Public License for more details.
@@ -14,9 +14,9 @@
 #  with this program; if not, write to the Free Software Foundation, Inc.,
 #  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
 #
-# slackbuild for GConf, by Rudson R. Alves
+# slackbuild for linux-pam, by Alexandre Vieira de Souza
 # requires:  
-# tested: GConf-2.26.2
+# tested: linux-pam-1.1.0
 # model: generic.mkSlackBuild $Rev: 822 $
 #
 
@@ -29,21 +29,21 @@ fi
 
 # Set variables
 CWD="$(pwd)"
-SRC_NAME="GConf"
-PKG_NAME="GConf"
+SRC_NAME="Linux-PAM"
+PKG_NAME="linux-pam"
 ARCH=${ARCH:=i486}
-SRC_VERSION=${VERSION:=2.26.2}
+SRC_VERSION=${VERSION:=1.1.0}
 PKG_VERSION="$(echo "$SRC_VERSION" | tr '[[:blank:]-]' '_')"
-BUILD=${BUILD:=1rra}
+BUILD=${BUILD:=1avs}
 SRC_DIR=${SRC_DIR:=$CWD}/$PKG_NAME
 TMP=${TMP:=/tmp}
 PKG=${PKG:=$TMP/package-$PKG_NAME}
 REPOS=${REPOS:=$TMP}
-SLACKBUILD_PATH=${SLACKBUILD_PATH:="gnome/base/gconf"}
+SLACKBUILD_PATH=${SLACKBUILD_PATH:="sys/libs/linux-pam"}
 PREFIX=${PREFIX:=/usr}
 PKG_WORK="$TMP/$SRC_NAME"
 CONF_OPTIONS=${CONF_OPTIONS:=""}
-NUMJOBS=${NUMJOBS:="-j7"}
+NUMJOBS=${NUMJOBS:=""}
 
 # Set system libraries' path and optmization flags based on $ARCH
 LIBDIR="$PREFIX/lib"
@@ -81,11 +81,63 @@ mkdir -p "$PKG_WORK" || exit $ERROR_MKDIR
 
 # Dowload source if necessary
 SRC="$SRC_NAME-$VERSION.tar.bz2"
-URL="http://ftp.acc.umu.se/pub/gnome/sources/GConf/2.26/$SRC"
+URL="ftp://ftp.kernel.org/pub/linux/libs/pam/library/$SRC"
 
 if [ ! -s "$SRC_DIR/$SRC" ] || ! bunzip2 -t "$SRC_DIR/$SRC" 2> /dev/null; then
   wget "$URL" -O "$SRC_DIR/$SRC" || exit $ERROR_WGET
 fi
+
+# Import minimized signing key from
+if echo [[SIGNING KEY URL]] | grep -q -v "SIGNING KEY URL"; then
+  lynx -dump [[SIGNING KEY URL]] | gpg --import || exit $ERROR_GPG
+elif echo 517D0F0E | grep -q -v "SIGNING KEY ID"; then
+  gpg --recv-keys 517D0F0E || exit $ERROR_GPG
+else
+  gpg --import << EOKEY || exit $ERROR_GPG
+[[SIGNING KEY]]
+EOKEY
+fi
+
+# Download source's signature if necessary and check it
+if echo [[SIGNING URL]] | grep -q -v "SIGNING URL"; then
+  SIGNATURE="`basename [[SIGNING URL]]`"
+  if [ ! -s "$SRC_DIR/$SIGNATURE" ]; then
+    wget "[[SIGNING URL]]" -O "$SRC_DIR/$SIGNATURE" || exit $ERROR_WGET
+  fi
+else
+  if [ -s "$SRC_DIR/$SRC.sig" ]; then
+    SIGNATURE="$SRC.sig"
+  elif [ -s "$SRC_DIR/$SRC.asc" ]; then
+    SIGNATURE="$SRC.asc"
+  elif [ -s "$SRC_DIR/$SRC.sign" ]; then
+    SIGNATURE="$SRC.sign"
+  else
+    echo Trying to get signature file from $URL.sig...
+    if wget "$URL.sig" -O "$SRC_DIR/$SRC.sig"; then
+      SIGNATURE="$SRC.sig"
+    else
+      rm $SRC_DIR/$SRC.sig
+      echo Trying to get signature file from $URL.asc...
+      if wget "$URL.asc" -O "$SRC_DIR/$SRC.asc"; then
+        SIGNATURE="$SRC.asc"
+      else
+        rm $SRC_DIR/$SRC.asc
+        echo Trying to get signature file from $URL.sign...
+        if wget "$URL.sign" -O "$SRC_DIR/$SRC.sign"; then
+          SIGNATURE="$SRC.sign"
+        else
+          rm $SRC_DIR/$SRC.sign
+          echo "Error getting source's signature file"
+          exit $ERROR_GPG
+        fi
+      fi
+    fi
+  fi
+fi
+
+echo Checking $SRC_DIR/$SRC with gpg using $SRC_DIR/$SIGNATURE...
+gpg --verify "$SRC_DIR/$SIGNATURE" "$SRC_DIR/$SRC" || exit $ERROR_GPG
+echo Success.
 
 # Check Manifest file
 if [ -e "$CWD/Manifest" ]; then
@@ -180,7 +232,7 @@ make install DESTDIR="$PKG" || exit $ERROR_INSTALL
 )
 
 # Install documentation
-DOCS="ABOUT-NLS AUTHORS COPYING ChangeLog INSTALL NEWS README TODO"
+DOCS="NEWS TODO README AUTHORS INSTALL ChangeLog MAINTAINERS COPYING LICENSE SIGNATURE readme.*"
 mkdir -p "$PKG/usr/doc/$PKG_NAME-$PKG_VERSION" || exit $ERROR_MKDIR
 for doc in $DOCS; do
   if [ -f "$doc" ]; then
@@ -198,25 +250,19 @@ cat << EODESC > "$PKG/install/slack-desc"
 # make exactly 11 lines for the formatting to be correct.  It's also
 # customary to leave one space after the ':'.
 
-     |-----handy-ruler--------------------------------------------------------|
-gconf: gconf by Slack.Sarava
-gconf:
-gconf: GConf is a configuration database system, functionally similar to the
-gconf: Windows registry but lots better. :-) It's being written for the GNOME
-gconf: desktop but does not require GNOME; configure should notice if GNOME
-gconf: is not installed and compile the basic GConf library anyway.
-gconf:
-gconf:
-gconf:
-gconf:
-gconf:
+         |-----handy-ruler----------------------------------------------------|
+linux-pam: Pluggable Authentication Modules for Linux
+linux-pam:
+linux-pam: Linux-PAM is a free implementation of the sun RFC for solaris.
+linux-pam: Basically, it is a flexible mechanism for authenticating users. 
+linux-pam: PAM provides a way to develop programs that are independent of
+linux-pam: authentication scheme. These programs need "authentication modules" 
+linux-pam: to be attatched to them at run-time in order to work. Which 
+linux-pam: authentication module is to be attatched is dependent upon the local 
+linux-pam: system setup and is at the discretion of the local system administrator.
+linux-pam:
+linux-pam: by xdoctor
 EODESC
-
-# Copy slack-required
-mkdir -p "$PKG/install" || exit $ERROR_MKDIR
-if [ -f "$CWD/slack-required" ]; then
-  cp $CWD/slack-required $PKG/install
-fi
 
 # Build the package
 cd "$PKG"
