backupninja: no, this is hopefully the last backupninja commit of the day :PP
git-svn-id: svn+slack://slack.fluxo.info/var/svn/slackbuilds@247 370017ae-e619-0410-ac65-c121f96126d4

diff --git a/backupninja/rub b/backupninja/rub
--- a/backupninja/rub
+++ b/backupninja/rub
@@ -141,12 +141,18 @@ for SECTION in $include; do
 
   if [ "$from" == "local" ]; then
     $rsync $EXCLUDES /$SECTION/ $backupdir/$SECTION/$section.0/ >> $log
+    if [ "$?" != "0" ];
+      error "Rsync error when trying to transfer $SECTION"
+    fi
   elif [ "$from" == "remote" ]; then
     if [ -z "$user" ] || [ -z "$host" ]; then
       error "Config file error: either user or host was not specified"
       exit 1
     else
       $rsync $EXCLUDES -e "$ssh" $user@$host:/$SECTION/ $backupdir/$SECTION/$section.0 >> $log
+      if [ "$?" != "0' ];
+        error "Rsync error when trying to transfer $SECTION"
+      fi
     fi
   else
     error "Invalid source $from"
