newsbeuter: adding newsbeuter; wyrd: adding wyrd; remind: adding remind; ddclient: adding ddclient; inadyn: adding inadyn
git-svn-id: svn+slack://slack.fluxo.info/var/svn/slackbuilds@2230 370017ae-e619-0410-ac65-c121f96126d4

diff --git a/x11/misc/remind/remind.SlackBuild b/x11/misc/remind/remind.SlackBuild
--- a/x11/misc/remind/remind.SlackBuild
+++ b/x11/misc/remind/remind.SlackBuild
@@ -1,23 +1,23 @@
 #!/bin/bash
 #
-#  perl-tree-dag_node.SlackBuild is free software; you can redistribute
+#  remind.SlackBuild is free software; you can redistribute
 #  it and/or modify it under the terms of the GNU General Public License as
 #  published by the Free Software Foundation; either version 2 of the License,
 #  or any later version.
 #
-#  perl-tree-dag_node.SlackBuild is distributed in the hope that it will
+#  remind.SlackBuild is distributed in the hope that it will
 #  be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
 #  Public License for more details.
 #
-#  You should have received a copy of the GNU General Public License along with
-#  this program; if not, write to the Free Software Foundation, Inc., 59 Temple
-#  Place - Suite 330, Boston, MA 02111-1307, USA
+#  You should have received a copy of the GNU General Public License along
+#  with this program; if not, write to the Free Software Foundation, Inc.,
+#  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
 #
-# slackbuild for perl-tree-dag_node, by Silvio Rhatto
+# slackbuild for remind, by Silvio Rhatto
 # requires:  
-# tested: perl-tree-dag_node-1.06
-# model: perl.mkSlackBuild $Rev: 796 $
+# tested: remind-03.01.07
+# model: generic.mkSlackBuild $Rev: 805 $
 #
 
 # Look for slackbuildrc
@@ -29,17 +29,17 @@ fi
 
 # Set variables
 CWD="$(pwd)"
-SRC_NAME="Tree-DAG_Node"
-PKG_NAME="perl-tree-dag_node"
+SRC_NAME="remind"
+PKG_NAME="remind"
 ARCH=${ARCH:=i486}
-SRC_VERSION=${VERSION:=1.06}
+SRC_VERSION=${VERSION:=03.01.07}
 PKG_VERSION="$(echo "$SRC_VERSION" | tr '[[:blank:]-]' '_')"
 BUILD=${BUILD:=1rha}
 SRC_DIR=${SRC_DIR:=$CWD}/$PKG_NAME
 TMP=${TMP:=/tmp}
 PKG=${PKG:=$TMP/package-$PKG_NAME}
 REPOS=${REPOS:=$TMP}
-SLACKBUILD_PATH=${SLACKBUILD_PATH:="dev/perl/perl-tree-dag_node"}
+SLACKBUILD_PATH=${SLACKBUILD_PATH:="x11/misc/remind"}
 PREFIX=${PREFIX:=/usr}
 PKG_WORK="$TMP/$SRC_NAME"
 CONF_OPTIONS=${CONF_OPTIONS:=""}
@@ -49,16 +49,17 @@ NUMJOBS=${NUMJOBS:=""}
 LIBDIR="$PREFIX/lib"
 
 if [ "$ARCH" = "i386" ]; then
-  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
+  SLKCFLAGS="-O2 -march=i386 -mtune=i686"
 elif [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mcpu=i686"
+  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686"
 elif [ "$ARCH" = "s390" ]; then
   SLKCFLAGS="-O2"
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2"
+  SLKCFLAGS="-O2 -fPIC"
   LIBDIR="$PREFIX/lib64"
+  LDFLAGS="-L/lib64 -L/usr/lib64"
 fi
 
 # Set error codes (used by createpkg)
@@ -69,7 +70,7 @@ ERROR_PATCH=40;     ERROR_VCS=41;       ERROR_MKDIR=42
 ERROR_MANIFEST=43;
 
 # Clean up any leftovers of previous builds
-rm -rf "$PKG_SRC" 2> /dev/null
+rm -rf "$PKG_WORK" 2> /dev/null
 rm -rf "$PKG" 2> /dev/null
 
 # Create directories if necessary
@@ -80,11 +81,55 @@ mkdir -p "$PKG_WORK" || exit $ERROR_MKDIR
 
 # Dowload source if necessary
 SRC="$SRC_NAME-$VERSION.tar.gz"
-URL="http://search.cpan.org/CPAN/authors/id/C/CO/COGENT/$SRC"
+URL="http://www.roaringpenguin.com/files/download/$SRC"
 
 if [ ! -s "$SRC_DIR/$SRC" ] || ! gunzip -t "$SRC_DIR/$SRC" 2> /dev/null; then
   wget "$URL" -O "$SRC_DIR/$SRC" || exit $ERROR_WGET
 fi
+
+# Import minimized signing key from
+if echo [[SIGNING KEY URL]] | grep -q -v "SIGNING KEY URL"; then
+  lynx -dump [[SIGNING KEY URL]] | gpg --import || exit $ERROR_GPG
+elif echo 126F42E0 | grep -q -v "SIGNING KEY ID"; then
+  gpg --recv-keys 126F42E0 || exit $ERROR_GPG
+else
+  gpg --import << EOKEY || exit $ERROR_GPG
+[[SIGNING KEY]]
+EOKEY
+fi
+
+# Download source's signature if necessary and check it
+if echo [[SIGNING URL]] | grep -q -v "SIGNING URL"; then
+  SIGNATURE="`basename [[SIGNING URL]]`"
+  if [ ! -s "$SRC_DIR/$SIGNATURE" ]; then
+    wget "[[SIGNING URL]]" -O "$SRC_DIR/$SIGNATURE" || exit $ERROR_WGET
+  fi
+else
+  if [ -s "$SRC_DIR/$SRC.sig" ]; then
+    SIGNATURE="$SRC.sig"
+  elif [ -s "$SRC_DIR/$SRC.asc" ]; then
+    SIGNATURE="$SRC.asc"
+  else
+    echo Trying to get signature file from $URL.sig...
+    if wget "$URL.sig" -O "$SRC_DIR/$SRC.sig"; then
+      SIGNATURE="$SRC.sig"
+    else
+      rm $SRC_DIR/$SRC.sig
+      echo Trying to get signature file from $URL.asc...
+      if wget "$URL.asc" -O "$SRC_DIR/$SRC.asc"; then
+        SIGNATURE="$SRC.asc"
+      else
+        rm $SRC_DIR/$SRC.asc
+        echo "Error getting source's signature file"
+        exit $ERROR_GPG
+      fi
+    fi
+  fi
+fi
+
+echo Checking $SRC_DIR/$SRC with gpg using $SRC_DIR/$SIGNATURE...
+gpg --verify "$SRC_DIR/$SIGNATURE" "$SRC_DIR/$SRC" || exit $ERROR_GPG
+echo Success.
 
 # Check Manifest file
 if [ -e "$CWD/Manifest" ]; then
@@ -130,7 +175,7 @@ if [ -e "$CWD/Manifest" ]; then
     fi
 
     # Check source code integrity
-    for ALGO in md5 sha1 sha256 sha512 rmd160; do
+    for ALGO in md5 rmd160 sha1 sha256 sha512; do
       if [ $ALGO = "rmd160" ]; then
         ALGO_SRC="`openssl rmd160 $MANIFEST_FILE | awk '{ print $2 }'`"
       else
@@ -155,24 +200,20 @@ fi
 # Untar
 cd "$PKG_WORK"
 tar --no-same-owner --no-same-permissions -xvf "$SRC_DIR/$SRC" || exit $ERROR_TAR
-PKG_SRC=`ls -l | awk '/^d/ { print $8 }'`
+PKG_SRC="$PWD/`ls -l | awk '/^d/ { print $NF }'`"
 cd "$PKG_SRC"
 
 # Configure
-perl Makefile.PL || exit $ERROR_CONF
+CFLAGS="$SLKCFLAGS" \
+  CXXFLAGS="$SLKCFLAGS" \
+  ./configure \
+  --prefix="$PREFIX" --libdir="$LIBDIR" $CONF_OPTIONS || exit $ERROR_CONF
 
 # Compile
 make $NUMJOBS || exit $ERROR_MAKE
 
 # Install
 make install DESTDIR="$PKG" || exit $ERROR_INSTALL
-
-# Fix .packlist
-string="`echo $PKG | sed -e 's/\//\\\\\//g'`"
-for file in `find $PKG -name .packlist`; do
-  sed -e "s/^$string//g" $file > $file.tmp
-  mv $file.tmp $file
-done
 
 # Strip binaries
 ( cd "$PKG"
@@ -182,8 +223,23 @@ done
     xargs strip --strip-unneeded 2> /dev/null
 )
 
+# Compress and link manpages
+if [ -d "$PKG/$PREFIX/man" ]; then
+  ( cd "$PKG/$PREFIX/man"
+    for manpagedir in $(find . -type d -name "man*") ; do
+      ( cd $manpagedir
+        for eachpage in $( find . -type l -maxdepth 1) ; do
+          ln -s $( readlink $eachpage ).gz $eachpage.gz
+          rm $eachpage
+        done
+        gzip -9 *.?
+      )
+    done
+  )
+fi
+
 # Install documentation
-DOCS="NEWS TODO README AUTHORS INSTALL ChangeLog MAINTAINERS COPYING LICENSE SIGNATURE readme.*"
+DOCS="COPYRIGHT README"
 mkdir -p "$PKG/usr/doc/$PKG_NAME-$PKG_VERSION" || exit $ERROR_MKDIR
 for doc in $DOCS; do
   if [ -f "$doc" ]; then
@@ -195,24 +251,24 @@ done
 mkdir -p "$PKG/install" || exit $ERROR_MKDIR
 cat << EODESC > "$PKG/install/slack-desc"
 # HOW TO EDIT THIS FILE:
-# The "handy ruler" below makes it easier to edit a package description.  Line
+# The "handy ruler" below makes it easier to edit a package description. Line
 # up the first '|' above the ':' following the base package name, and the '|'
-# on the right side marks the last column you can put a character in.  You must
+# on the right side marks the last column you can put a character in. You must
 # make exactly 11 lines for the formatting to be correct.  It's also
 # customary to leave one space after the ':'.
 
-             _    |-----handy-ruler-------------------------------------------|
-perl-tree-dag_node: perl-tree-dag_node ((super)class for representing nodes in a tree)
-perl-tree-dag_node:
-perl-tree-dag_node:
-perl-tree-dag_node:
-perl-tree-dag_node:
-perl-tree-dag_node:
-perl-tree-dag_node:
-perl-tree-dag_node:
-perl-tree-dag_node:
-perl-tree-dag_node:
-perl-tree-dag_node:
+      |-----handy-ruler-------------------------------------------------------|
+remind: remind
+remind:
+remind: Remind is a sophisticated calendar and alarm program.
+remind:
+remind:
+remind:
+remind:
+remind:
+remind:
+remind:
+remind:
 EODESC
 
 # Build the package
