gibak: rebuilt from mkbuild
git-svn-id: svn+slack://slack.fluxo.info/var/svn/slackbuilds@1927 370017ae-e619-0410-ac65-c121f96126d4

diff --git a/app/backup/gibak/gibak.SlackBuild b/app/backup/gibak/gibak.SlackBuild
--- a/app/backup/gibak/gibak.SlackBuild
+++ b/app/backup/gibak/gibak.SlackBuild
@@ -91,10 +91,10 @@ PKG_SRC="$PWD/`ls -l | awk '/^d/ { print $NF }'`"
 cd "$PKG_SRC"
 
 # Build and install package
-echo "INCLUDES += $LIBDIR" > OMakefile.new
-cat OMakefile > OMakefile.new
-mv OMakefile.new OMakefile
-omake
+echo "INCLUDES += $LIBDIR" > OMakefile.new || exit $ERROR_MAKE
+cat OMakefile > OMakefile.new || exit $ERROR_MAKE
+mv OMakefile.new OMakefile || exit $ERROR_MAKE
+omake || exit $ERROR_MAKE
 
 # Strip binaries
 ( cd "$PKG"
