Syncing with generic.SlackBuild v0.8.2
git-svn-id: svn+slack://slack.fluxo.info/var/svn/slackbuilds@1164 370017ae-e619-0410-ac65-c121f96126d4

diff --git a/sci/electronics/gtkwave/gtkwave.SlackBuild b/sci/electronics/gtkwave/gtkwave.SlackBuild
--- a/sci/electronics/gtkwave/gtkwave.SlackBuild
+++ b/sci/electronics/gtkwave/gtkwave.SlackBuild
@@ -27,6 +27,8 @@ PKG=${PKG:=$TMP/package-$PKG_NAME}
 REPOS=${REPOS:=$TMP}
 PREFIX=${PREFIX:=/usr}
 PKG_SRC="$TMP/$SRC_NAME-$SRC_VERSION"
+CONF_OPTIONS=${CONF_OPTIONS:=}
+NUMJOBS=${NUMJOBS:=-j4}
 
 # Set error codes (used by createpkg)
 ERROR_WGET=31;      ERROR_MAKE=32;      ERROR_INSTALL=33
@@ -72,10 +74,10 @@ tar --no-same-owner --no-same-permissions -xvf "$SRC_DIR/$SRC" || exit $ERROR_TA
 cd "$PKG_SRC"
 
 # Configure
-echo $GTK_VERSION | ./configure || exit $ERROR_CONF
+echo $GTK_VERSION | ./configure "$CONF_OPTIONS" || exit $ERROR_CONF
 
 # Compile
-make || exit $ERROR_MAKE
+make "$NUMJOBS" || exit $ERROR_MAKE
 
 # Install
 make install prefix="$PKG/$PREFIX" || exit $ERROR_INSTALL
@@ -105,8 +107,8 @@ fi
 
 # Install documentation
 DOCS="*.TXT doc/gtkwave.odt examples"
-mkdir -p "$PKG/$PREFIX/doc/$PKG_NAME-$PKG_VERSION" || exit $ERROR_MKDIR
-cp -a $DOCS "$PKG/$PREFIX/doc/$PKG_NAME-$PKG_VERSION"
+mkdir -p "$PKG/usr/doc/$PKG_NAME-$PKG_VERSION" || exit $ERROR_MKDIR
+cp -a $DOCS "$PKG/usr/doc/$PKG_NAME-$PKG_VERSION"
 
 # Add package description (slack-desc)
 mkdir -p "$PKG/install" || exit $ERROR_MKDIR
